"""
pipeline/exporter.py - Multi-format Data Export Pipeline
Wildlife Intelligence Monitoring System
"""
import io
import json
import logging
from pathlib import Path
from typing import Optional

import pandas as pd

logger = logging.getLogger(__name__)

EXPORTS_DIR = Path(__file__).parent.parent / "data" / "exports"
EXPORTS_DIR.mkdir(parents=True, exist_ok=True)


class DataExporter:
    """Handles export of wildlife data to multiple file formats."""

    def to_csv(self, df: pd.DataFrame) -> bytes:
        """Export dataframe to CSV bytes."""
        return df.to_csv(index=False).encode("utf-8")

    def to_json(self, df: pd.DataFrame) -> bytes:
        """Export dataframe to JSON bytes (records orientation)."""
        records = df.to_dict(orient="records")
        return json.dumps(records, indent=2, default=str).encode("utf-8")

    def to_excel(self, df: pd.DataFrame) -> bytes:
        """Export dataframe to Excel (.xlsx) bytes."""
        buffer = io.BytesIO()
        with pd.ExcelWriter(buffer, engine="xlsxwriter") as writer:
            df.to_excel(writer, index=False, sheet_name="Wildlife Data")
            # Auto-adjust column widths
            worksheet = writer.sheets["Wildlife Data"]
            for i, col in enumerate(df.columns):
                max_len = max(df[col].astype(str).map(len).max(), len(col)) + 2
                worksheet.set_column(i, i, min(max_len, 40))
        return buffer.getvalue()

    def to_parquet(self, df: pd.DataFrame) -> bytes:
        """Export dataframe to Parquet bytes."""
        buffer = io.BytesIO()
        # Convert all object columns to string for Parquet compatibility
        df_export = df.copy()
        for col in df_export.select_dtypes(include="object").columns:
            df_export[col] = df_export[col].astype(str)
        df_export.to_parquet(buffer, index=False)
        return buffer.getvalue()

    def to_sql_dump(self, df: pd.DataFrame) -> bytes:
        """Generate SQL INSERT statements for the animals table."""
        lines = [
            "-- Wildlife Intelligence Monitoring System - SQL Dump",
            "-- Generated by WIMS Export System",
            "",
            "CREATE TABLE IF NOT EXISTS animals_export (",
        ]
        # Column definitions
        col_defs = []
        for col in df.columns:
            dtype = df[col].dtype
            if pd.api.types.is_float_dtype(dtype):
                sql_type = "REAL"
            elif pd.api.types.is_integer_dtype(dtype):
                sql_type = "INTEGER"
            else:
                sql_type = "TEXT"
            col_defs.append(f"    {col} {sql_type}")
        lines.append(",\n".join(col_defs))
        lines.append(");")
        lines.append("")

        # INSERT statements
        for _, row in df.iterrows():
            cols = ", ".join(df.columns)
            vals = []
            for v in row:
                if pd.isna(v) or v is None:
                    vals.append("NULL")
                elif isinstance(v, (int, float)):
                    vals.append(str(v))
                else:
                    escaped = str(v).replace("'", "''")
                    vals.append(f"'{escaped}'")
            lines.append(f"INSERT INTO animals_export ({cols}) VALUES ({', '.join(vals)});")

        return "\n".join(lines).encode("utf-8")

    def save_to_disk(self, df: pd.DataFrame, format: str, filename: str) -> Path:
        """Save export file to the exports directory."""
        exporters = {
            "csv": (self.to_csv, ".csv"),
            "json": (self.to_json, ".json"),
            "xlsx": (self.to_excel, ".xlsx"),
            "parquet": (self.to_parquet, ".parquet"),
            "sql": (self.to_sql_dump, ".sql"),
        }
        if format not in exporters:
            raise ValueError(f"Unsupported format: {format}")

        fn, ext = exporters[format]
        path = EXPORTS_DIR / f"{filename}{ext}"
        path.write_bytes(fn(df))
        logger.info(f"Exported {format} to {path}")
        return path
